language: java
before_install:
- sudo apt-get update
- sudo apt-get install build-essential automake autoconf libtool pkg-config
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -y -qq gcc-4.8 g++-4.8
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
jdk:
- openjdk7
os:
- linux
install: "cd tools ; ./install ; cd .."
script: "mvn clean ; mvn -DskipTests -DskipNarTests -DskipNarJniTests -PskipNarTestsCompile install"

notifications:
 email: false
